#!/usr/bin/env python3
"""
Generate src/ui_icons_data.c from ASCII art.

Same reasoning as the font generator: bitmap data is only reviewable if you can
see it. --preview prints every icon back.

Output layout is row-major, MSB leftmost, each row padded to a byte boundary —
which is what ui_gfx_bitmap expects.

    ./test/gen_icons.py --preview
    ./test/gen_icons.py > ../src/ui_icons_data.c
"""
import sys

# The paper plane, which is what a Telegram client should open with. Drawn at
# 29x24 — big enough to read as the logo on a 64-pixel-tall screen while leaving
# room for a title and a caption underneath.
LOGO = """
.........................##..
.......................#####.
.....................########
...................##########
.................#######.####
...............#######...####
.............#######....####.
...........#######.....####..
.........#######......####...
.......#######.......####....
.....#######........####.....
...#######.........####......
.#######..........####.......
######...........####........
.####...........####.........
..####.........####..........
...####.......####...........
....####.....####............
.....####...####.............
......####.####..............
.......######................
........####.................
.........##..................
..........#..................
"""

# A single tick, and the double tick that means "read". Telegram's own
# distinction, and the one users actually look for.
CHECK = """
......#
.....##
....##.
#..##..
##.##..
.####..
..##...
"""

DCHECK = """
...#...#
..##..##
.##..##.
##..##..
#..##...
..###...
.##.....
"""

# Shown on the 2FA step.
LOCK = """
.####.
#....#
#....#
######
##..##
##..##
######
"""

BACK = """
..#..
.##..
####.
.##..
..#..
"""

SEND = """
#.....
###...
#####.
######
#####.
###...
#.....
"""

# Eight frames of a rotating dot ring: the connect and 2FA steps both take
# seconds, and a still screen reads as a hang.
SPINNER = [
"""
..###..
.#...#.
#.....#
#.....#
#.....#
.#...#.
..###..
""",
"""
..###..
.#...##
#.....#
#.....#
#.....#
.#...#.
..###..
""",
"""
..###..
.#...#.
#.....#
#.....##
#.....#
.#...#.
..###..
""",
"""
..###..
.#...#.
#.....#
#.....#
#.....#
.#...##
..###..
""",
"""
..###..
.#...#.
#.....#
#.....#
#.....#
.#...#.
..####.
""",
"""
..###..
.#...#.
#.....#
#.....#
#.....#
.##..#.
..###..
""",
"""
..###..
.#...#.
##....#
#.....#
##....#
.#...#.
..###..
""",
"""
..###..
.##..#.
#.....#
#.....#
#.....#
.#...#.
..###..
""",
]

# Status bar furniture.
BATTERY = """
#########.
#.......#.
#.......##
#.......##
#.......##
#.......#.
#########.
"""

LINK_ON = """
..###..
.#...#.
#..#..#
...#...
..###..
..###..
...#...
"""

LINK_OFF = """
#.....#
.#...#.
..#.#..
...#...
..#.#..
.#...#.
#.....#
"""

# Placeholder shown where a chat has an avatar we cannot render.
PERSON = """
..###..
.#...#.
.#...#.
..###..
.#####.
#.....#
#.....#
"""

ICONS = [
    ("logo",     LOGO),
    ("check",    CHECK),
    ("dcheck",   DCHECK),
    ("lock",     LOCK),
    ("back",     BACK),
    ("send",     SEND),
    ("battery",  BATTERY),
    ("link_on",  LINK_ON),
    ("link_off", LINK_OFF),
    ("person",   PERSON),
]


def parse(art):
    rows = [r for r in art.strip('\n').split('\n') if r]
    h = len(rows)
    w = max(len(r) for r in rows)
    stride = (w + 7) // 8
    data = bytearray(stride * h)
    for y, row in enumerate(rows):
        for x, ch in enumerate(row):
            if ch == '#':
                data[y * stride + (x >> 3)] |= 0x80 >> (x & 7)
    return w, h, bytes(data)


def preview():
    for name, art in ICONS:
        w, h, data = parse(art)
        stride = (w + 7) // 8
        print(f"{name}  {w}x{h}  {len(data)} bytes")
        for y in range(h):
            line = ''.join(
                '#' if data[y * stride + (x >> 3)] & (0x80 >> (x & 7)) else '.'
                for x in range(w))
            print('   ' + line)
    total = sum(len(parse(a)[2]) for _, a in ICONS)
    total += sum(len(parse(a)[2]) for a in SPINNER)
    for i, art in enumerate(SPINNER):
        w, h, data = parse(art)
        if i == 0:
            print(f"spinner  {w}x{h}  {len(data)} bytes x {len(SPINNER)} frames")
    print(f"\ntotal icon data: {total} bytes")


def emit():
    out = []
    w_ = out.append
    w_("/*")
    w_(" * ui_icons_data.c — icon bitmaps.")
    w_(" *")
    w_(" * GENERATED by test/gen_icons.py, DO NOT HAND-EDIT. The art lives in that")
    w_(" * script, which can print it back with --preview.")
    w_(" *")
    w_(" * Row-major, MSB leftmost, rows padded to a byte — the layout")
    w_(" * ui_gfx_bitmap reads.")
    w_(" */")
    w_('#include "ui_icons.h"')
    w_("")
    for name, art in ICONS:
        w, h, data = parse(art)
        body = ", ".join(f"0x{b:02X}" for b in data)
        w_(f"static const uint8_t {name}_bits[] = {{")
        # wrap at a sane width
        line = "    "
        for i, b in enumerate(data):
            piece = f"0x{b:02X},"
            if len(line) + len(piece) > 76:
                w_(line.rstrip())
                line = "    "
            line += piece + " "
        if line.strip():
            w_(line.rstrip())
        w_("};")
        w_(f"const ui_icon_t ui_icon_{name} = {{ {w}, {h}, {name}_bits }};")
        w_("")

    for i, art in enumerate(SPINNER):
        w, h, data = parse(art)
        body = ", ".join(f"0x{b:02X}" for b in data)
        w_(f"static const uint8_t spinner{i}_bits[] = {{ {body} }};")
    w_("")
    w_("const ui_icon_t ui_icon_spinner[UI_SPINNER_FRAMES] = {")
    for i, art in enumerate(SPINNER):
        w, h, _ = parse(art)
        w_(f"    {{ {w}, {h}, spinner{i}_bits }},")
    w_("};")
    return "\n".join(out) + "\n"


if __name__ == '__main__':
    if '--preview' in sys.argv:
        preview()
    else:
        sys.stdout.write(emit())
