/*
 * mtp_skip_data.c — TL field-layout tables.
 *
 * GENERATED by test/gen_skip.py from Telegram's official schema.
 * DO NOT HAND-EDIT — regenerate instead.
 *
 * See the header of that script for why this exists and why MessageMedia is
 * deliberately opaque. In short: a full skipper needs ~780 constructors and
 * will not fit the app pool; excluding the media types brings it to the
 * 152 below, and an opaque field is reported rather than mis-skipped.
 */
#include "mtp_skip.h"

#pragma GCC visibility push(hidden)

/* 703 fields, 152 constructors, 46 types */
const mtp_skip_field_t mtp_skip_fields[] = {
    { 0,0xFF,  0}, { 9,0x05,  0}, { 9,0x08,  0}, { 9,0x0A,  0}, { 3,0xFF,  0},
    { 3,0xFF,  0}, { 7,0xFF,  0}, { 2,0x10,  0}, { 0,0xFF,  0}, { 9,0x00,  0},
    { 9,0x02,  0}, { 9,0x05,  0}, { 9,0x07,  0}, { 9,0x08,  0}, { 9,0x09,  0},
    { 9,0x0B,  0}, { 9,0x0C,  0}, { 9,0x13,  0}, { 9,0x14,  0}, { 9,0x15,  0},
    { 9,0x16,  0}, { 9,0x17,  0}, { 9,0x18,  0}, { 9,0x19,  0}, { 9,0x1A,  0},
    { 9,0x1B,  0}, { 9,0x1C,  0}, { 9,0x1D,  0}, { 9,0x1E,  0}, { 1,0xFF,  0},
    { 9,0x21,  0}, { 9,0x22,  0}, { 9,0x23,  0}, { 9,0x2C,  0}, { 9,0x2F,  0},
    { 9,0x30,  0}, { 9,0x31,  0}, { 9,0x33,  0}, { 3,0xFF,  0}, { 3,0x0D,  0},
    { 7,0xFF,  0}, { 7,0x06,  0}, {10,0xFF,  3}, { 2,0xFF,  0}, {11,0x09, 36},
    {10,0x0E,  1}, {10,0x0F,  2}, {10,0x12,  2}, { 2,0x11,  0}, {11,0x20, 44},
    {10,0x24, 33}, {10,0x27, 29}, {10,0x28, 29}, {10,0x29,  6}, { 2,0x2A,  0},
    { 2,0x2B,  0}, { 3,0x2D,  0}, { 3,0x2E,  0}, { 3,0x32,  0}, { 3,0xFF,  0},
    { 0,0xFF,  0}, { 9,0x00,  0}, { 9,0x02,  0}, { 9,0x05,  0}, { 9,0x17,  0},
    { 9,0x18,  0}, { 9,0x19,  0}, { 3,0xFF,  0}, { 7,0xFF,  0}, {10,0xFF,  3},
    { 2,0xFF,  0}, { 2,0xFF,  0}, { 2,0xFF,  0}, {10,0x06, 11}, {10,0x0E,  1},
    {10,0x12,  2}, { 3,0xFF,  0}, { 7,0xFF,  0}, { 0,0xFF,  0}, { 9,0x00,  0},
    { 9,0x01,  0}, { 9,0x02,  0}, { 9,0x03,  0}, { 9,0x04,  0}, { 9,0x05,  0},
    { 9,0x07,  0}, { 9,0x09,  0}, { 9,0x0A,  0}, { 9,0x0B,  0}, { 9,0x0C,  0},
    { 9,0x0D,  0}, { 9,0x0E,  0}, { 9,0x0F,  0}, { 9,0x10,  0}, { 9,0x11,  0},
    { 9,0x12,  0}, { 0,0xFF,  0}, { 9,0x00,  0}, { 9,0x01,  0}, { 9,0x02,  0},
    { 9,0x03,  0}, { 9,0x04,  0}, { 9,0x05,  0}, { 9,0x06,  0}, { 9,0x07,  0},
    { 9,0x08,  0}, { 9,0x0A,  0}, { 9,0x0F,  0}, { 9,0x11,  0}, { 9,0x12,  0},
    { 9,0x13,  0}, { 9,0x14,  0}, { 9,0x15,  0}, { 9,0x16,  0}, { 9,0x17,  0},
    { 9,0x18,  0}, { 9,0x19,  0}, { 9,0x1A,  0}, { 2,0xFF,  0}, { 0,0xFF,  0},
    { 9,0x00,  0}, { 3,0xFF,  0}, { 7,0x01,  0}, { 2,0xFF,  0}, { 0,0xFF,  0},
    { 9,0x02,  0}, {10,0xFF,  8}, {10,0xFF, 28}, { 2,0xFF,  0}, { 2,0xFF,  0},
    { 2,0xFF,  0}, { 2,0xFF,  0}, { 2,0xFF,  0}, { 0,0xFF,  0}, { 9,0x02,  0},
    { 9,0x03,  0}, { 9,0x06,  0}, {10,0xFF, 28}, { 2,0xFF,  0}, { 2,0xFF,  0},
    { 2,0xFF,  0}, { 2,0xFF,  0}, { 2,0xFF,  0}, { 2,0xFF,  0}, {10,0xFF, 30},
    { 2,0x00,  0}, {10,0x01,  5}, { 2,0x04,  0}, { 2,0x05,  0}, { 0,0xFF,  0},
    { 2,0x00,  0}, { 0,0xFF,  0}, { 9,0x01,  0}, { 9,0x06,  0}, {10,0x04, 13},
    { 7,0xFF,  0}, {11,0x03, 19}, {15,0x05,  0}, { 2,0xFF,  0}, { 3,0x07,  0},
    {10,0x08, 39}, { 0,0xFF,  0}, { 3,0xFF,  0}, { 2,0x00,  0}, { 0,0xFF,  0},
    { 3,0xFF,  0}, { 3,0xFF,  0}, { 7,0xFF,  0}, { 7,0xFF,  0}, { 3,0xFF,  0},
    { 2,0xFF,  0}, { 2,0xFF,  0}, { 2,0xFF,  0}, { 2,0xFF,  0}, { 2,0x00,  0},
    { 0,0xFF,  0}, { 3,0xFF,  0}, { 2,0x00,  0}, { 0,0xFF,  0}, { 9,0x00,  0},
    { 7,0x01,  0}, {10,0x01, 40}, { 3,0xFF,  0}, { 0,0xFF,  0}, { 9,0x00,  0},
    { 9,0x01,  0}, { 9,0x02,  0}, { 2,0xFF,  0}, { 7,0xFF,  0}, {10,0x03,  3},
    { 2,0xFF,  0}, { 0,0xFF,  0}, { 9,0x01,  0}, { 9,0x02,  0}, { 9,0x03,  0},
    { 9,0x05,  0}, { 9,0x06,  0}, { 9,0x07,  0}, { 2,0xFF,  0}, { 2,0xFF,  0},
    {10,0xFF, 28}, { 7,0xFF,  0}, { 2,0xFF,  0}, { 3,0x00,  0}, { 2,0xFF,  0},
    { 2,0xFF,  0}, { 2,0xFF,  0}, { 2,0xFF,  0}, { 2,0xFF,  0}, { 2,0xFF,  0},
    {10,0xFF, 28}, {10,0xFF, 30}, {10,0x04,  5}, {10,0xFF, 12}, { 2,0xFF,  0},
    { 3,0xFF,  0}, { 3,0xFF,  0}, { 3,0xFF,  0}, { 3,0xFF,  0}, { 3,0xFF,  0},
    { 3,0xFF,  0}, {10,0xFF, 12}, { 2,0xFF,  0}, { 3,0xFF,  0}, {10,0xFF, 12},
    { 2,0xFF,  0}, { 3,0xFF,  0}, { 3,0xFF,  0}, { 3,0xFF,  0}, {10,0xFF, 12},
    { 2,0xFF,  0}, {10,0xFF, 12}, { 0,0xFF,  0}, { 2,0xFF,  0}, { 2,0x00,  0},
    {10,0x01, 12}, { 7,0x02,  0}, {11,0x03, 19}, { 2,0x04,  0}, {10,0x05, 12},
    { 2,0x06,  0}, {10,0xFF, 12}, { 2,0xFF,  0}, { 3,0xFF,  0}, { 3,0xFF,  0},
    { 3,0xFF,  0}, { 0,0xFF,  0}, { 9,0x00,  0}, { 9,0x01,  0}, { 9,0x02,  0},
    {10,0x0A, 17}, { 7,0xFF,  0}, { 2,0xFF,  0}, {10,0xFF, 35}, { 2,0xFF,  0},
    { 0,0xFF,  0}, {10,0x0A, 17}, { 7,0xFF,  0}, { 0,0xFF,  0}, {10,0x0A, 17},
    { 7,0xFF,  0}, { 0,0xFF,  0}, {10,0x0A, 17}, { 7,0xFF,  0}, { 2,0xFF,  0},
    {10,0xFF, 35}, { 2,0xFF,  0}, { 0,0xFF,  0}, { 9,0x00,  0}, {10,0x0A, 17},
    { 7,0xFF,  0}, { 7,0x01,  0}, { 7,0xFF,  0}, {10,0xFF, 14}, { 0,0xFF,  0},
    {10,0x0A, 17}, { 8,0x00,  0}, { 7,0xFF,  0}, { 0,0xFF,  0}, {10,0x0A, 17},
    { 7,0xFF,  0}, { 0,0xFF,  0}, {10,0x0A, 17}, { 7,0xFF,  0}, {10,0xFF, 14},
    { 0,0xFF,  0}, {10,0x0A, 17}, { 7,0xFF,  0}, { 0,0xFF,  0}, { 9,0x00,  0},
    {10,0x0A, 17}, { 7,0xFF,  0}, { 7,0xFF,  0}, {11,0x01, 10}, { 0,0xFF,  0},
    {10,0x0A, 17}, { 7,0xFF,  0}, { 0,0xFF,  0}, {10,0x0A, 17}, { 7,0xFF,  0},
    { 7,0xFF,  0}, { 0,0xFF,  0}, {10,0x0A, 17}, { 7,0xFF,  0}, { 3,0xFF,  0},
    { 0,0xFF,  0}, {10,0x0A, 17}, { 7,0xFF,  0}, { 7,0xFF,  0}, { 0,0xFF,  0},
    {10,0x0A, 17}, { 7,0xFF,  0}, { 7,0xFF,  0}, { 0,0xFF,  0}, { 9,0x00,  0},
    {10,0x0A, 17}, { 7,0xFF,  0}, { 7,0xFF,  0}, { 0,0xFF,  0}, {10,0x0A, 17},
    { 7,0xFF,  0}, { 7,0xFF,  0}, { 0,0xFF,  0}, {10,0x0A, 17}, { 7,0xFF,  0},
    { 7,0x00,  0}, { 7,0xFF,  0}, { 2,0xFF,  0}, {11,0xFF, 15}, { 0,0xFF,  0},
    { 9,0x00,  0}, { 9,0x01,  0}, { 9,0x02,  0}, { 3,0x03,  0}, { 0,0xFF,  0},
    { 9,0x01,  0}, { 9,0x04,  0}, { 9,0x05,  0}, { 9,0x0D,  0}, { 9,0x0E,  0},
    { 9,0x12,  0}, { 9,0x13,  0}, { 9,0x15,  0}, { 9,0x18,  0}, { 9,0x1A,  0},
    { 9,0x1B,  0}, { 1,0xFF,  0}, { 9,0x21,  0}, { 9,0x24,  0}, { 9,0x28,  0},
    { 9,0x29,  0}, { 2,0xFF,  0}, {10,0x08, 28}, { 2,0x1D,  0}, { 7,0x2C,  0},
    {10,0xFF, 28}, {10,0x1C, 28}, {10,0x02, 20}, { 3,0x0B,  0}, { 3,0x20,  0},
    {10,0x03, 25}, { 2,0xFF,  0}, { 7,0xFF,  0}, {15,0x09,  0}, {10,0x06, 34},
    {11,0x07, 19}, { 2,0x0A,  0}, { 2,0x0A,  0}, {10,0x17, 24}, { 2,0x0F,  0},
    { 7,0x10,  0}, { 3,0x11,  0}, {10,0x14, 22}, {11,0x16, 36}, { 2,0x19,  0},
    { 2,0x1E,  0}, { 3,0x22,  0}, {10,0x23,  7}, { 2,0x25,  0}, { 3,0x26,  0},
    {10,0x27, 39}, { 2,0x2A,  0}, { 7,0x2B,  0}, { 0,0xFF,  0}, { 9,0x01,  0},
    { 9,0x04,  0}, { 9,0x05,  0}, { 9,0x09,  0}, { 9,0x0D,  0}, { 9,0x0E,  0},
    { 9,0x13,  0}, { 2,0xFF,  0}, {10,0x08, 28}, {10,0xFF, 28}, {10,0x1C, 28},
    {10,0x03, 25}, { 2,0xFF,  0}, {15,0xFF,  0}, {10,0x14, 22}, { 2,0x19,  0},
    { 0,0xFF,  0}, { 2,0xFF,  0}, {10,0x00, 28}, { 2,0xFF,  0}, { 2,0xFF,  0},
    {10,0xFF, 14}, { 2,0xFF,  0}, { 2,0xFF,  0}, { 2,0xFF,  0}, { 2,0xFF,  0},
    { 2,0xFF,  0}, { 2,0xFF,  0}, { 2,0xFF,  0}, { 2,0xFF,  0}, { 2,0xFF,  0},
    { 2,0xFF,  0}, { 2,0xFF,  0}, { 2,0xFF,  0}, { 2,0xFF,  0}, { 2,0xFF,  0},
    { 2,0xFF,  0}, { 2,0xFF,  0}, { 7,0xFF,  0}, { 2,0xFF,  0}, { 2,0xFF,  0},
    { 2,0xFF,  0}, { 2,0xFF,  0}, { 7,0xFF,  0}, { 2,0xFF,  0}, { 2,0xFF,  0},
    { 0,0xFF,  0}, { 9,0x00,  0}, { 9,0x01,  0}, { 9,0x02,  0}, { 9,0x03,  0},
    { 9,0x04,  0}, { 9,0x05,  0}, { 2,0xFF,  0}, { 2,0xFF,  0}, { 2,0xFF,  0},
    { 2,0xFF,  0}, { 2,0xFF,  0}, { 2,0xFF,  0}, { 2,0xFF,  0}, { 2,0xFF,  0},
    { 2,0xFF,  0}, { 2,0xFF,  0}, { 2,0xFF,  0}, { 2,0xFF,  0}, { 2,0xFF,  0},
    { 2,0xFF,  0}, { 2,0xFF,  0}, { 3,0xFF,  0}, { 2,0xFF,  0}, { 2,0xFF,  0},
    { 3,0xFF,  0}, { 0,0xFF,  0}, { 9,0x00,  0}, { 2,0xFF,  0}, { 2,0xFF,  0},
    { 2,0xFF,  0}, { 2,0xFF,  0}, { 0,0xFF,  0}, { 9,0x07,  0}, { 9,0x0B,  0},
    {10,0x00, 28}, { 7,0x05,  0}, { 2,0xFF,  0}, { 2,0x02,  0}, { 7,0x03,  0},
    {10,0x04, 28}, { 2,0x04,  0}, {10,0x08, 28}, { 7,0x09,  0}, { 2,0x0A,  0},
    { 7,0x06,  0}, { 0,0xFF,  0}, { 9,0x00,  0}, { 9,0x01,  0}, { 9,0x02,  0},
    {10,0xFF, 28}, { 2,0xFF,  0}, {10,0xFF, 31}, { 0,0xFF,  0}, { 9,0x00,  0},
    { 9,0x02,  0}, { 9,0x03,  0}, {11,0xFF, 32}, {11,0x01, 21}, {11,0x04, 23},
    { 0,0xFF,  0}, { 9,0x00,  0}, { 9,0x01,  0}, { 9,0x02,  0}, {10,0x03, 28},
    { 2,0xFF,  0}, { 0,0xFF,  0}, { 9,0x00,  0}, { 2,0xFF,  0}, { 2,0xFF,  0},
    {11,0x01, 28}, { 3,0x00,  0}, { 2,0x02,  0}, { 2,0x03,  0}, {10,0xFF, 28},
    { 2,0xFF,  0}, { 0,0xFF,  0}, { 9,0x02,  0}, { 9,0x03,  0}, { 9,0x09,  0},
    { 2,0x04,  0}, {10,0x00, 28}, {10,0x05, 20}, {15,0x08,  0}, { 2,0x01,  0},
    { 7,0x06,  0}, {11,0x07, 19}, { 2,0x0A,  0}, { 2,0x0B,  0}, { 7,0xFF,  0},
    { 7,0xFF,  0}, { 3,0xFF,  0}, { 7,0xFF,  0}, { 7,0xFF,  0}, { 2,0xFF,  0},
    { 7,0xFF,  0}, { 3,0xFF,  0}, { 3,0xFF,  0}, { 3,0xFF,  0}, { 0,0xFF,  0},
    { 2,0x00,  0}, { 3,0x01,  0}, { 3,0xFF,  0}, { 0,0xFF,  0}, { 3,0xFF,  0},
    { 3,0xFF,  0}, { 3,0xFF,  0}, { 2,0xFF,  0}, {12,0xFF,  0}, { 2,0x00,  0},
    {12,0x01,  0}, { 0,0xFF,  0}, { 8,0x00,  0}, { 8,0x01,  0}, { 2,0x02,  0},
    {10,0x03, 26}, {10,0x04, 26}, {10,0x05, 26}, { 8,0x06,  0}, { 8,0x07,  0},
    {10,0x08, 26}, {10,0x09, 26}, {10,0x0A, 26}, { 7,0xFF,  0}, { 3,0xFF,  0},
    { 0,0xFF,  0}, { 2,0x00,  0}, {10,0xFF, 31}, { 2,0xFF,  0}, { 0,0xFF,  0},
    { 9,0x00,  0}, { 2,0x01,  0}, {11,0xFF, 16}, { 0,0xFF,  0}, { 9,0x00,  0},
    { 9,0x01,  0}, { 9,0x02,  0}, { 9,0x04,  0}, {11,0xFF, 16}, { 7,0x03,  0},
    { 0,0xFF,  0}, { 9,0x01,  0}, { 9,0x02,  0}, { 7,0x03,  0}, { 0,0xFF,  0},
    { 9,0x02,  0}, { 0,0xFF,  0}, { 9,0x00,  0}, { 8,0x03,  0}, {10,0x01,  1},
    {10,0x02,  1}, { 0,0xFF,  0}, { 8,0x00,  0}, { 8,0x01,  0}, { 0,0xFF,  0},
    { 9,0x00,  0}, { 9,0x05,  0}, { 8,0x03,  0}, { 8,0x04,  0}, {10,0x01,  1},
    {10,0x02,  1}, { 7,0xFF,  0}, { 7,0xFF,  0}, { 7,0xFF,  0}, { 7,0xFF,  0},
    { 7,0xFF,  0}, { 3,0xFF,  0}, { 3,0xFF,  0}, { 2,0xFF,  0}, { 0,0xFF,  0},
    { 9,0x01,  0}, { 9,0x02,  0}, {10,0x03, 38}, { 2,0x00,  0}, { 7,0xFF,  0},
    {11,0xFF, 19}, { 0,0xFF,  0}, { 9,0x0A,  0}, { 9,0x0B,  0}, { 9,0x0C,  0},
    { 9,0x0D,  0}, { 9,0x0E,  0}, { 9,0x0F,  0}, { 9,0x10,  0}, { 9,0x11,  0},
    { 9,0x12,  0}, { 9,0x14,  0}, { 9,0x15,  0}, { 9,0x17,  0}, { 9,0x18,  0},
    { 9,0x19,  0}, { 9,0x1A,  0}, { 9,0x1B,  0}, { 9,0x1C,  0}, { 9,0x1D,  0},
    { 1,0xFF,  0}, { 9,0x21,  0}, { 9,0x22,  0}, { 9,0x23,  0}, { 9,0x24,  0},
    { 9,0x2A,  0}, { 9,0x2B,  0}, { 9,0x2D,  0}, { 9,0x30,  0}, { 9,0x31,  0},
    { 3,0xFF,  0}, { 3,0x00,  0}, { 7,0x01,  0}, { 7,0x02,  0}, { 7,0x03,  0},
    { 7,0x04,  0}, {10,0x05, 42}, {10,0x06, 43}, { 2,0x0E,  0}, {11,0x12, 36},
    { 7,0x13,  0}, { 7,0x16,  0}, {10,0x1E,  6}, {11,0x20, 44}, {10,0x25, 33},
    {10,0x28, 29}, {10,0x29, 29}, { 2,0x2C,  0}, { 3,0x2E,  0}, { 3,0x2F,  0},
    { 3,0xFF,  0}, { 0,0xFF,  0}, { 9,0x00,  0}, { 9,0x02,  0}, { 3,0xFF,  0},
    { 7,0x01,  0}, { 2,0xFF,  0}, { 2,0xFF,  0}, { 0,0xFF,  0}, { 9,0x00,  0},
    { 0,0xFF,  0}, { 9,0x00,  0}, { 0,0xFF,  0}, { 9,0x00,  0}, { 2,0xFF,  0},
    { 0,0xFF,  0}, { 9,0x00,  0}, { 9,0x01,  0}, { 7,0xFF,  0}, { 0,0xFF,  0},
    { 7,0x00,  0}, { 3,0x02,  0}, { 7,0x02,  0}, { 7,0x01,  0}, { 2,0x01,  0},
    { 2,0xFF,  0}, { 2,0xFF,  0}, { 2,0xFF,  0}, { 7,0xFF,  0}, { 2,0xFF,  0},
    { 0,0xFF,  0}, { 7,0x00,  0}, { 0,0xFF,  0}, { 9,0x00,  0}, { 9,0x01,  0},
    { 7,0xFF,  0}, { 0,0xFF,  0}, { 7,0x00,  0}, { 2,0xFF,  0}, { 7,0xFF,  0},
    { 2,0xFF,  0}, { 0,0xFF,  0}, { 9,0x00,  0}, { 9,0x01,  0}, { 7,0xFF,  0},
    { 2,0xFF,  0}, { 2,0x03,  0}, { 2,0x04,  0},
};

const mtp_skip_ctor_t mtp_skip_ctors[] = {
    { 0x17d493d5u,    0,  8 },   /* channelForbidden */
    { 0x1c32b11cu,    8, 51 },   /* channel */
    { 0x29562865u,   59,  1 },   /* chatEmpty */
    { 0x41cbf256u,   60, 16 },   /* chat */
    { 0x6592a1a7u,   76,  2 },   /* chatForbidden */
    { 0x5fb224d5u,   78, 18 },   /* chatAdminRights */
    { 0x9f120418u,   96, 23 },   /* chatBannedRights */
    { 0x1c6e1c11u,  119,  5 },   /* chatPhoto */
    { 0x37c1011cu,  124,  0 },   /* chatPhotoEmpty */
    { 0x71bd134cu,  124,  9 },   /* dialogFolder */
    { 0xd58a08c6u,  133, 16 },   /* dialog */
    { 0x1b0c841au,  149,  2 },   /* draftMessageEmpty */
    { 0x96eaa5ebu,  151, 10 },   /* draftMessage */
    { 0x07141dbfu,  161,  3 },   /* inputEmojiStatusCollectible */
    { 0x2de11aaeu,  164,  0 },   /* emojiStatusEmpty */
    { 0x7184603bu,  164, 11 },   /* emojiStatusCollectible */
    { 0xe7ff068au,  175,  3 },   /* emojiStatus */
    { 0xb89bfccfu,  178,  5 },   /* factCheck */
    { 0xff544e65u,  183,  7 },   /* folder */
    { 0x023f109bu,  190,  1 },   /* forumTopicDeleted */
    { 0xcdff0ecau,  191, 22 },   /* forumTopic */
    { 0x0e3b2d0cu,  213,  0 },   /* inlineQueryPeerTypeBotPM */
    { 0x3081ed9du,  213,  0 },   /* inlineQueryPeerTypeSameBotPM */
    { 0x5ec4be43u,  213,  0 },   /* inlineQueryPeerTypeMegagroup */
    { 0x6334ee9au,  213,  0 },   /* inlineQueryPeerTypeBroadcast */
    { 0x833c0facu,  213,  0 },   /* inlineQueryPeerTypePM */
    { 0xd766c50au,  213,  0 },   /* inlineQueryPeerTypeChat */
    { 0x5b934f9du,  213,  3 },   /* inputChannelFromMessage */
    { 0xee8c1e86u,  216,  0 },   /* inputChannelEmpty */
    { 0xf35aec28u,  216,  2 },   /* inputChannel */
    { 0x27bcbbfcu,  218,  2 },   /* inputPeerChannel */
    { 0x35a95cb9u,  220,  1 },   /* inputPeerChat */
    { 0x7da07ec9u,  221,  0 },   /* inputPeerSelf */
    { 0x7f3b18eau,  221,  0 },   /* inputPeerEmpty */
    { 0xa87b0a1cu,  221,  3 },   /* inputPeerUserFromMessage */
    { 0xbd2a0840u,  224,  3 },   /* inputPeerChannelFromMessage */
    { 0xdde8a54cu,  227,  2 },   /* inputPeerUser */
    { 0x5881323au,  229,  2 },   /* inputReplyToStory */
    { 0x69d66c45u,  231,  1 },   /* inputReplyToMonoForum */
    { 0x869fbe10u,  232,  9 },   /* inputReplyToMessage */
    { 0x1da448e2u,  241,  3 },   /* inputUserFromMessage */
    { 0xb98886cfu,  244,  0 },   /* inputUserEmpty */
    { 0xf21158c6u,  244,  2 },   /* inputUser */
    { 0xf7c1b13fu,  246,  0 },   /* inputUserSelf */
    { 0x02b78156u,  246,  9 },   /* inputKeyboardButtonRequestPeer */
    { 0x3fa53905u,  255,  3 },   /* keyboardButtonBuy */
    { 0x417efd8fu,  258,  3 },   /* keyboardButtonRequestPhone */
    { 0x5b0f15f5u,  261,  6 },   /* keyboardButtonRequestPeer */
    { 0x68013e72u,  267,  7 },   /* inputKeyboardButtonUrlAuth */
    { 0x7a11d782u,  274,  4 },   /* keyboardButtonRequestPoll */
    { 0x7d170cffu,  278,  3 },   /* keyboardButton */
    { 0x7d5e07c7u,  281,  4 },   /* inputKeyboardButtonUserProfile */
    { 0x89c590f9u,  285,  3 },   /* keyboardButtonGame */
    { 0x991399fcu,  288,  6 },   /* keyboardButtonSwitchInline */
    { 0xaa40f94du,  294,  3 },   /* keyboardButtonRequestGeoLocation */
    { 0xbcc4af10u,  297,  4 },   /* keyboardButtonCopy */
    { 0xc0fd5d09u,  301,  4 },   /* keyboardButtonUserProfile */
    { 0xd80c25ecu,  305,  4 },   /* keyboardButtonUrl */
    { 0xe15c4370u,  309,  4 },   /* keyboardButtonSimpleWebView */
    { 0xe62bc960u,  313,  5 },   /* keyboardButtonCallback */
    { 0xe846b1a0u,  318,  4 },   /* keyboardButtonWebView */
    { 0xf51006f9u,  322,  6 },   /* keyboardButtonUrlAuth */
    { 0x77608b83u,  328,  1 },   /* keyboardButtonRow */
    { 0x4fdd3430u,  329,  5 },   /* keyboardButtonStyle */
    { 0x3ae56482u,  334, 49 },   /* message */
    { 0x7a800e0au,  383, 17 },   /* messageService */
    { 0x90a6ca84u,  400,  3 },   /* messageEmpty */
    { 0x208e68c9u,  403,  3 },   /* inputMessageEntityMentionName */
    { 0x28a20571u,  406,  2 },   /* messageEntityCode */
    { 0x32ca960fu,  408,  2 },   /* messageEntitySpoiler */
    { 0x4c4e743fu,  410,  2 },   /* messageEntityCashtag */
    { 0x64e475c2u,  412,  2 },   /* messageEntityEmail */
    { 0x6cef8ac7u,  414,  2 },   /* messageEntityBotCommand */
    { 0x6ed02538u,  416,  2 },   /* messageEntityUrl */
    { 0x6f635b0du,  418,  2 },   /* messageEntityHashtag */
    { 0x73924be0u,  420,  3 },   /* messageEntityPre */
    { 0x761e6af4u,  423,  2 },   /* messageEntityBankCard */
    { 0x76a6d327u,  425,  3 },   /* messageEntityTextUrl */
    { 0x826f8b60u,  428,  2 },   /* messageEntityItalic */
    { 0x904ac7c7u,  430, 10 },   /* messageEntityFormattedDate */
    { 0x9b69e34bu,  440,  2 },   /* messageEntityPhone */
    { 0x9c4e7e8bu,  442,  2 },   /* messageEntityUnderline */
    { 0xbb92ba95u,  444,  2 },   /* messageEntityUnknown */
    { 0xbd610bc9u,  446,  2 },   /* messageEntityBold */
    { 0xbf0693d4u,  448,  2 },   /* messageEntityStrike */
    { 0xc8cf05f8u,  450,  3 },   /* messageEntityCustomEmoji */
    { 0xdc7b1140u,  453,  3 },   /* messageEntityMentionName */
    { 0xf1ccaaacu,  456,  4 },   /* messageEntityBlockquote */
    { 0xfa04579du,  460,  2 },   /* messageEntityMention */
    { 0x4e4df4bbu,  462, 14 },   /* messageFwdHeader */
    { 0x8c79b63cu,  476,  7 },   /* messagePeerReaction */
    { 0x0a339f0bu,  483,  7 },   /* messageReactions */
    { 0x4ba3a95au,  490,  6 },   /* messageReactor */
    { 0x83d60fc2u,  496,  8 },   /* messageReplies */
    { 0x0e5af939u,  504,  2 },   /* messageReplyStoryHeader */
    { 0x6917560bu,  506, 13 },   /* messageReplyHeader */
    { 0x6f0c34dfu,  519,  0 },   /* notificationSoundNone */
    { 0x830b9ae4u,  519,  2 },   /* notificationSoundLocal */
    { 0x97e8bebeu,  521,  0 },   /* notificationSoundDefault */
    { 0xff6c8049u,  521,  1 },   /* notificationSoundRingtone */
    { 0x3a912d4au,  522,  4 },   /* passwordKdfAlgoSHA256SHA256PBKDF2HMACSHA512iter100000SHA256ModPow */
    { 0xd45ab096u,  526,  0 },   /* passwordKdfAlgoUnknown */
    { 0x36c6019au,  526,  1 },   /* peerChat */
    { 0x59511722u,  527,  1 },   /* peerUser */
    { 0xa2a5371eu,  528,  1 },   /* peerChannel */
    { 0xb54b5acfu,  529,  3 },   /* peerColor */
    { 0xb8ea86a9u,  532,  1 },   /* inputPeerColorCollectible */
    { 0xb9c0639au,  533,  8 },   /* peerColorCollectible */
    { 0x99622c0cu,  541, 12 },   /* peerNotifySettings */
    { 0x1b2286b8u,  553,  1 },   /* reactionEmoji */
    { 0x523da4ebu,  554,  0 },   /* reactionPaid */
    { 0x79f5d419u,  554,  0 },   /* reactionEmpty */
    { 0x8935fc73u,  554,  1 },   /* reactionCustomEmoji */
    { 0xa3d1cb80u,  555,  4 },   /* reactionCount */
    { 0x711d692du,  559,  3 },   /* recentStory */
    { 0x48a30254u,  562,  1 },   /* replyInlineMarkup */
    { 0x85dd99d1u,  563,  7 },   /* replyKeyboardMarkup */
    { 0x86b40b08u,  570,  4 },   /* replyKeyboardForceReply */
    { 0xa03e5b85u,  574,  2 },   /* replyKeyboardHide */
    { 0x339bef6cu,  576,  5 },   /* requestPeerTypeBroadcast */
    { 0x5f3b8a00u,  581,  3 },   /* requestPeerTypeUser */
    { 0xc9f06e1bu,  584,  7 },   /* requestPeerTypeChat */
    { 0xd072acb4u,  591,  3 },   /* restrictionReason */
    { 0x004a8537u,  594,  0 },   /* securePasswordKdfAlgoUnknown */
    { 0x86471d92u,  594,  1 },   /* securePasswordKdfAlgoSHA512 */
    { 0xbbf2dda0u,  595,  1 },   /* securePasswordKdfAlgoPBKDF2HMACSHA512iter100000 */
    { 0x74aee3e0u,  596,  1 },   /* starsTonAmount */
    { 0xbbb6b4a3u,  597,  2 },   /* starsAmount */
    { 0x0e8e37e5u,  599,  5 },   /* suggestedPost */
    { 0x751f3146u,  604,  2 },   /* textWithEntities */
    { 0x31774388u,  606, 49 },   /* user */
    { 0xd3bc4b7au,  655,  1 },   /* userEmpty */
    { 0x4f11bae1u,  656,  0 },   /* userProfilePhotoEmpty */
    { 0x82d1f706u,  656,  6 },   /* userProfilePhoto */
    { 0x008c703fu,  662,  1 },   /* userStatusOffline */
    { 0x09d05049u,  663,  0 },   /* userStatusEmpty */
    { 0x541a1d1au,  663,  2 },   /* userStatusLastWeek */
    { 0x65899777u,  665,  2 },   /* userStatusLastMonth */
    { 0x7b197dc8u,  667,  2 },   /* userStatusRecently */
    { 0xedb93949u,  669,  1 },   /* userStatusOnline */
    { 0xb4073647u,  670,  4 },   /* username */
    { 0x009fd736u,  674,  7 },   /* auth.sentCodeTypeFirebaseSms */
    { 0x3dbb5986u,  681,  1 },   /* auth.sentCodeTypeApp */
    { 0x5353e5a7u,  682,  1 },   /* auth.sentCodeTypeCall */
    { 0x82006484u,  683,  2 },   /* auth.sentCodeTypeMissedCall */
    { 0xa416ac81u,  685,  2 },   /* auth.sentCodeTypeSmsWord */
    { 0xa5491deau,  687,  3 },   /* auth.sentCodeTypeSetUpEmailRequired */
    { 0xab03c6d9u,  690,  1 },   /* auth.sentCodeTypeFlashCall */
    { 0xb37794afu,  691,  2 },   /* auth.sentCodeTypeSmsPhrase */
    { 0xc000bba2u,  693,  1 },   /* auth.sentCodeTypeSms */
    { 0xd9565c39u,  694,  2 },   /* auth.sentCodeTypeFragmentSms */
    { 0xf450f59bu,  696,  7 },   /* auth.sentCodeTypeEmailCode */
};

const mtp_skip_type_t mtp_skip_types[] = {
    {    0,  5 },   /* MTP_T_CHAT = Chat */
    {    5,  1 },   /* MTP_T_CHATADMINRIGHTS = ChatAdminRights */
    {    6,  1 },   /* MTP_T_CHATBANNEDRIGHTS = ChatBannedRights */
    {    7,  2 },   /* MTP_T_CHATPHOTO = ChatPhoto */
    {    9,  2 },   /* MTP_T_DIALOG = Dialog */
    {   11,  2 },   /* MTP_T_DRAFTMESSAGE = DraftMessage */
    {   13,  4 },   /* MTP_T_EMOJISTATUS = EmojiStatus */
    {   17,  1 },   /* MTP_T_FACTCHECK = FactCheck */
    {   18,  1 },   /* MTP_T_FOLDER = Folder */
    {   19,  2 },   /* MTP_T_FORUMTOPIC = ForumTopic */
    {   21,  6 },   /* MTP_T_INLINEQUERYPEERTYPE = InlineQueryPeerType */
    {   27,  3 },   /* MTP_T_INPUTCHANNEL = InputChannel */
    {   30,  7 },   /* MTP_T_INPUTPEER = InputPeer */
    {   37,  3 },   /* MTP_T_INPUTREPLYTO = InputReplyTo */
    {   40,  4 },   /* MTP_T_INPUTUSER = InputUser */
    {   44, 18 },   /* MTP_T_KEYBOARDBUTTON = KeyboardButton */
    {   62,  1 },   /* MTP_T_KEYBOARDBUTTONROW = KeyboardButtonRow */
    {   63,  1 },   /* MTP_T_KEYBOARDBUTTONSTYLE = KeyboardButtonStyle */
    {   64,  3 },   /* MTP_T_MESSAGE = Message */
    {   67, 22 },   /* MTP_T_MESSAGEENTITY = MessageEntity */
    {   89,  1 },   /* MTP_T_MESSAGEFWDHEADER = MessageFwdHeader */
    {   90,  1 },   /* MTP_T_MESSAGEPEERREACTION = MessagePeerReaction */
    {   91,  1 },   /* MTP_T_MESSAGEREACTIONS = MessageReactions */
    {   92,  1 },   /* MTP_T_MESSAGEREACTOR = MessageReactor */
    {   93,  1 },   /* MTP_T_MESSAGEREPLIES = MessageReplies */
    {   94,  2 },   /* MTP_T_MESSAGEREPLYHEADER = MessageReplyHeader */
    {   96,  4 },   /* MTP_T_NOTIFICATIONSOUND = NotificationSound */
    {  100,  2 },   /* MTP_T_PASSWORDKDFALGO = PasswordKdfAlgo */
    {  102,  3 },   /* MTP_T_PEER = Peer */
    {  105,  3 },   /* MTP_T_PEERCOLOR = PeerColor */
    {  108,  1 },   /* MTP_T_PEERNOTIFYSETTINGS = PeerNotifySettings */
    {  109,  4 },   /* MTP_T_REACTION = Reaction */
    {  113,  1 },   /* MTP_T_REACTIONCOUNT = ReactionCount */
    {  114,  1 },   /* MTP_T_RECENTSTORY = RecentStory */
    {  115,  4 },   /* MTP_T_REPLYMARKUP = ReplyMarkup */
    {  119,  3 },   /* MTP_T_REQUESTPEERTYPE = RequestPeerType */
    {  122,  1 },   /* MTP_T_RESTRICTIONREASON = RestrictionReason */
    {  123,  3 },   /* MTP_T_SECUREPASSWORDKDFALGO = SecurePasswordKdfAlgo */
    {  126,  2 },   /* MTP_T_STARSAMOUNT = StarsAmount */
    {  128,  1 },   /* MTP_T_SUGGESTEDPOST = SuggestedPost */
    {  129,  1 },   /* MTP_T_TEXTWITHENTITIES = TextWithEntities */
    {  130,  2 },   /* MTP_T_USER = User */
    {  132,  2 },   /* MTP_T_USERPROFILEPHOTO = UserProfilePhoto */
    {  134,  6 },   /* MTP_T_USERSTATUS = UserStatus */
    {  140,  1 },   /* MTP_T_USERNAME = Username */
    {  141, 11 },   /* MTP_T_AUTH_SENTCODETYPE = auth.SentCodeType */
};

const size_t mtp_skip_type_count = sizeof(mtp_skip_types) / sizeof(mtp_skip_types[0]);

#pragma GCC visibility pop
